export const pastPaperData = [
  {
    id: 1,
    course: "Computer Science 101",
    courseCode: "CS101",
    university: "Harvard University",
    subject: "Computer Science",
    examYear: 2023,
    description: "Introductory computer science exam covering algorithms, data structures, and basic programming concepts.",
    coverImage: "https://source.unsplash.com/random/300x400/?computer,science",
    rating: 4.8,
    views: 12500,
    downloads: 8700,
    pages: 12,
    trending: true,
    newUpload: false,
    questions: 45,
    timeAllowed: "3 hours",
    solutionsAvailable: true
  },
  {
    id: 2,
    course: "Advanced Calculus",
    courseCode: "MATH302",
    university: "MIT",
    subject: "Mathematics",
    examYear: 2022,
    description: "Final examination covering multivariable calculus, differential equations, and vector analysis.",
    coverImage: "https://source.unsplash.com/random/300x400/?mathematics,calculus",
    rating: 4.6,
    views: 9800,
    downloads: 6500,
    pages: 15,
    trending: true,
    newUpload: false,
    questions: 38,
    timeAllowed: "2.5 hours",
    solutionsAvailable: true
  },
  {
    id: 3,
    course: "Molecular Biology",
    courseCode: "BIO205",
    university: "Stanford University",
    subject: "Biology",
    examYear: 2023,
    description: "Midterm exam covering DNA replication, transcription, translation, and gene regulation.",
    coverImage: "https://source.unsplash.com/random/300x400/?biology,dna",
    rating: 4.5,
    views: 7500,
    downloads: 4200,
    pages: 10,
    trending: false,
    newUpload: true,
    questions: 30,
    timeAllowed: "2 hours",
    solutionsAvailable: false
  },
  {
    id: 4,
    course: "Macroeconomics",
    courseCode: "ECON201",
    university: "University of Chicago",
    subject: "Economics",
    examYear: 2021,
    description: "Comprehensive final exam covering GDP, inflation, unemployment, and fiscal policy.",
    coverImage: "https://source.unsplash.com/random/300x400/?economics,money",
    rating: 4.3,
    views: 6800,
    downloads: 3900,
    pages: 14,
    trending: false,
    newUpload: false,
    questions: 42,
    timeAllowed: "3 hours",
    solutionsAvailable: true
  },
  {
    id: 5,
    course: "Organic Chemistry",
    courseCode: "CHEM220",
    university: "UC Berkeley",
    subject: "Chemistry",
    examYear: 2023,
    description: "Second semester organic chemistry exam focusing on reaction mechanisms and synthesis.",
    coverImage: "https://source.unsplash.com/random/300x400/?chemistry,organic",
    rating: 4.7,
    views: 9200,
    downloads: 5800,
    pages: 16,
    trending: true,
    newUpload: false,
    questions: 35,
    timeAllowed: "2.5 hours",
    solutionsAvailable: true
  },
  {
    id: 6,
    course: "Artificial Intelligence",
    courseCode: "CS470",
    university: "Carnegie Mellon",
    subject: "Computer Science",
    examYear: 2022,
    description: "Graduate level exam covering machine learning, neural networks, and AI ethics.",
    coverImage: "https://source.unsplash.com/random/300x400/?ai,robotics",
    rating: 4.9,
    views: 11500,
    downloads: 7900,
    pages: 18,
    trending: true,
    newUpload: false,
    questions: 28,
    timeAllowed: "3 hours",
    solutionsAvailable: true
  },
  {
    id: 7,
    course: "Quantum Physics",
    courseCode: "PHYS450",
    university: "Caltech",
    subject: "Physics",
    examYear: 2023,
    description: "Advanced quantum mechanics exam covering wave functions, operators, and quantum states.",
    coverImage: "https://source.unsplash.com/random/300x400/?quantum,physics",
    rating: 4.4,
    views: 6200,
    downloads: 3100,
    pages: 13,
    trending: false,
    newUpload: true,
    questions: 25,
    timeAllowed: "2.5 hours",
    solutionsAvailable: false
  },
  {
    id: 8,
    course: "International Law",
    courseCode: "LAW310",
    university: "Yale University",
    subject: "Law",
    examYear: 2021,
    description: "Final exam covering treaties, international organizations, and human rights law.",
    coverImage: "https://source.unsplash.com/random/300x400/?law,justice",
    rating: 4.2,
    views: 5400,
    downloads: 2900,
    pages: 11,
    trending: false,
    newUpload: false,
    questions: 40,
    timeAllowed: "3 hours",
    solutionsAvailable: true
  },
  {
    id: 9,
    course: "Neuroscience",
    courseCode: "BIO330",
    university: "Johns Hopkins",
    subject: "Biology",
    examYear: 2023,
    description: "Exam covering neuroanatomy, neural signaling, and cognitive functions.",
    coverImage: "https://source.unsplash.com/random/300x400/?neuroscience,brain",
    rating: 4.6,
    views: 7100,
    downloads: 3800,
    pages: 14,
    trending: false,
    newUpload: true,
    questions: 32,
    timeAllowed: "2 hours",
    solutionsAvailable: false
  },
  {
    id: 10,
    course: "Data Structures",
    courseCode: "CS202",
    university: "Princeton University",
    subject: "Computer Science",
    examYear: 2022,
    description: "Midterm exam on arrays, linked lists, trees, graphs, and sorting algorithms.",
    coverImage: "https://source.unsplash.com/random/300x400/?data,structures",
    rating: 4.7,
    views: 10300,
    downloads: 6700,
    pages: 12,
    trending: true,
    newUpload: false,
    questions: 36,
    timeAllowed: "2 hours",
    solutionsAvailable: true
  },
  {
    id: 11,
    course: "Political Theory",
    courseCode: "POL210",
    university: "Oxford University",
    subject: "Political Science",
    examYear: 2021,
    description: "Exam covering major political thinkers from Plato to Rawls.",
    coverImage: "https://source.unsplash.com/random/300x400/?politics,government",
    rating: 4.1,
    views: 4800,
    downloads: 2400,
    pages: 10,
    trending: false,
    newUpload: false,
    questions: 30,
    timeAllowed: "2 hours",
    solutionsAvailable: true
  },
  {
    id: 12,
    course: "Biochemistry",
    courseCode: "CHEM310",
    university: "University of Cambridge",
    subject: "Chemistry",
    examYear: 2023,
    description: "Final exam covering metabolic pathways, enzyme kinetics, and molecular biology techniques.",
    coverImage: "https://source.unsplash.com/random/300x400/?biochemistry,lab",
    rating: 4.5,
    views: 6900,
    downloads: 3600,
    pages: 15,
    trending: false,
    newUpload: true,
    questions: 34,
    timeAllowed: "3 hours",
    solutionsAvailable: false
  }
];