export const DEFAULT_BOOK_CATEGORIES = [
  '110_Good_Books_to_Read',
  '50-eBooks',
  '6-Essential-Books-Featuring-Dinosaurs-in-Science-Fiction',
  'Aerospace',
  'Agriculture',
  'Agriculture2',
  'Algebra',
  'Algorithms',
  'Analytical-Chemistry',
  'Applied-Genetics-and-Molecular-Biology',
  'Applied_Math',
  'aquantum',
  'Archaeology',
  'Art Of Comp',
  'ASP-Dot-NET',
  'Astrobiology',
  'ats',
  'AWS-Books',
  'Best-Investing',
  'bio',
  'Biology',
  'Biomedical_Informatics',
  'Biophysics',
  'Biostatistics',
  'Biotechnology',
  'bk',
  'Books_About_Stars',
  'C-Sharp-Programming',
  'Calculus',
  'Chemical-Engineering',
  'Customer CRM',
  'Cyber Security',
  'Database',
  'Dentistry incop',
  'Earth-Sciences',
  'eBooks',
  'Ec',
  'Econ',
  'Economics',
  'Electrical_and_Electronics',
  'Electrochemistry',
  'Embedded Systems',
  'Encyclopedia',
  'Engineering',
  'Entomology',
  'Epidemiology-Books',
  'Epistemology',
  'Essay-Writing',
  '25_Computer',
  'Accountancy',
  'Acoustics',
  'Agrochemistry',
  'AI',
  'AI Books',
  'Animal_Biotechnology',
  'Animal_Husbandry',
  'Anthropology',
  'Arboriculture',
  'Archaeoastronomy',
  'Architecture',
  'Astrochemistry',
  'Astrometry',
  'Astronautics-Books',
  'Atmospheric_Chemistry',
  'Atomic-Physics',
  'Automation-Testing',
  'Automobile_Engineering',
  'Bacteriology',
  'Behavioral_Science',
  'Biochemistry',
  'Bioinformatics',
  'Bioinorganic_Chemistry',
  'Biolinguistics',
  'Biomechanics',
  'Blockchain',
  'Books-to-Learn-R-and-Data-Science',
  'Books_Mars',
  'Boolean_Algebra',
  'Botany',
  'Bryology',
  'Business_Intelligence',
  'C',
  'Cancer',
  'Cardiology',
  'comp',
  'cplu',
  'Cartesian_Geometry',
  'CCNA_CCNP',
  'Cell_Biology',
  'Chemical-Kinetics',
  'Chronobiology',
  'Chronology',
  'Civil-Engineering',
  'Classical_Physics',
  'Combiratorics',
  'Comp _Science',
  'Compiler',
  'Computational_Chemistry',
  'Computational_Physics',
  'Computer',
  'Computer-Graphics',
  'Computer_Vision',
  'Condensed_Matter_Physics',
  'Cosmochemistry',
  'Cosmology',
  'CPP',
  'CPP Exercise',
  'Cryptography',
  'CSS_HTML',
  'ctb',
  'Data-Mining',
  'Data-Warehousing',
  'Dendroecology',
  'Dermatology',
  'dev',
  'devops',
  'Differential C',
  'Discrete-Mathematics',
  'Ecology',
  'Electronics',
  'Embryology',
  'Entrepreneurship',
  'Enzymology',
  'Epigenetics',
  'Ethology',
  'Evolution',
  'Exobiology',
  'Face_Recognition',
  'Formal_Semantics',
  'Game_Theory',
  'Genetics',
  'Genomics',
  'Geochemistry',
  'Geography',
  'Geophysics',
  'Gerontology',
  'GO',
  'Hardware',
  'Herpetology',
  'Heuristics',
  'Ichthyology',
  'Immunology',
  'Julia',
  'Kotlin',
  'Linux',
  'Material-Science',
  'Mathe',
  'Mensuration',
  'Metallurgy',
  'Metaphysics',
  'Meteorology',
  'Microservices',
  'Modern_Physics',
  'MongoDB',
  'Mycology',
  'Nanotechnology',
  'Nasa',
  'Nematology',
  'Networking',
  'Neurobiolog',
  'Neurochemistry',
  'Neurology',
  'New folder',
  'Nuclear_Phyc',
  'Nuera_Net',
  'Nutrition',
  'Periodic_Table',
  'Pharmacognosy',
  'Pharmacovigilance',
  'Photonics',
  'PhP',
  'Probability',
  'Public_Administration',
  'Python',
  'Radiobiology',
  'Robotics',
  'Ruby-Programming',
  'Scala-Programming',
  'Taxonomy',
  'Telecommunications',
  'TensorFlow',
  'Text_Mining',
  'Thermal_Phy',
  'Thermochemistry',
  'Thermodynamics',
  'The_Greatest_Books',
  'TK',
  'TN',
  'Topology',
  'Top_technology',
  'Toxicology',
  'Track Control',
  'Trigonometry',
  'User Interface',
  'Virology',
  'Volcanology',
  'Web-Designing',
  'WorldWar',
  'Femtochemistry',
  'Forensic_Science',
  'Forestry',
  'General_Knowledge',
  'Geology',
  'Git',
  'Graph_Theory',
  'Green_Chemistry',
  'h',
  'Histology',
  'History',
  'Homeostasis',
  'Human_Anatomy',
  'IIT_JEE_Chemistry',
  'Important_Philosophy',
  'Integral_Calculus',
  'Investing',
  'j',
  'Java',
  'jQuery',
  'JS',
  'k',
  'kl',
  'Kn',
  'KP',
  'l',
  'Laser',
  'Law',
  'Lichenology',
  'Biodiversity',
  'Biometrics',
  'Biophysical_Chemistry',
  'chem',
  'Cognitive',
  'Data_Technology',
  'English_Grammar',
  'm',
  'Ned',
  'p',
  'Sed',
  'y',
  'z',
  'Evolutionary_Biology',
  'Finance',
  'Genetic_Programming',
  'Horticulture',
  'Invention',
  'IOT',
  'Mammalogy',
  'Marine_Biology',
  'Mechanics',
  'Philosophy',
  'Physiology',
  'Primatology',
  'Quantum_Field',
  'Rocket_Science',
  'Surface_Chemistry',
  'Theoretical-Computer-Science',
  'Math',
  'Mathematical-Biology',
  'Mathematical-Logic',
  'Mathematical-Physics',
  'Matlab',
  'Matrix_Algebra',
  'Max-Born',
  'Mechanical-Engineering',
  'Med',
  'Medical',
  'Medicinal-Plants',
  'Mesoscopic_Physics',
  'Microbiology',
  'Mth',
  'n',
  'NCERT',
  'New folder',
  'Novels',
  'NuclearMagnetic Resonance',
  'o',
  'OA Astronomy',
  'OA Botany',
  'OA Chemistry',
  'OA Economics',
  'OA Physics',
  'Objective-C-Programming',
  'Oceanography',
  'Oct',
  'OK',
  'ol',
  'Oncology',
  'Ontology',
  'OP',
  'Optics',
  'Organic-Chemistry',
  'Organometallic_Chemistry',
  'Ornithology',
  'os',
  'OSB',
  'Paleontology',
  'Parasitology',
  'Particle P',
  'Pathology',
  'Pattern_Recognition',
  'Petroleum_Engineering',
  'Pharmacy',
  'Philosophy',
  'Philosophy 2',
  'Photobiology',
  'Phycology',
  'Physical-Chemistry',
  'Physics',
  'Phytogeography',
  'pl',
  'Plant_Biotechnology',
  'Plasma_Physics',
  'Political_Science',
  'Popular_Science',
  'Protozoology',
  'PS',
  'Psychobiology',
  'Psychophysics',
  'PY',
  'Quantum',
  'Quantum _M',
  'Quantum-Chemistry',
  'Quantum_Biology',
  'Quantum_Chromodynamics',
  'Radiochemistry',
  'React',
  'Robotic_Process_Automati',
  'Science',
  'Sci_Fic',
  'Seismology',
  'Serology',
  'Silcon Valley',
  'Social_Psychology',
  'Soil_Biology',
  'Solid-State-Chemistry',
  'Space',
  'Spectroscopy',
  'SQL',
  'Statistics',
  'Stereochemistry',
  'Synthetic_Chemistry',
  'XML',
  'Zoology',
];

export const normalizeCategoryName = (value = '') => String(value || '').replace(/\s+/g, ' ').trim().toLowerCase();

export const UNIQUE_DEFAULT_BOOK_CATEGORIES = Array.from(
  new Map(
    DEFAULT_BOOK_CATEGORIES.map((name) => {
      const normalized = String(name || '').replace(/\s+/g, ' ').trim();
      return [normalizeCategoryName(normalized), normalized];
    })
  ).values()
);

export const isSyntheticCategoryId = (id) => typeof id === 'string' && id.startsWith('default-');

export const mergeBookCategories = (items = []) => {
  const normalized = new Map();
  const merged = [...(items || [])].filter(item => !isSyntheticCategoryId(item?.id));

  for (const item of merged) {
    const name = (item?.name || '').replace(/\s+/g, ' ').trim();
    if (!name) continue;
    normalized.set(normalizeCategoryName(name), item);
  }

  if (merged.length === 0) {
    const fallback = UNIQUE_DEFAULT_BOOK_CATEGORIES.map((name) => ({
      id: `default-${normalizeCategoryName(name).replace(/[^a-z0-9]+/g, '-')}`,
      name,
      description: '',
      bookCount: 0,
      isDefault: true,
    }));

    return fallback.sort((a, b) => (a.name || '').localeCompare(b.name || '', undefined, { sensitivity: 'base' }));
  }

  return merged.sort((a, b) => (a.name || '').localeCompare(b.name || '', undefined, { sensitivity: 'base' }));
};

export async function seedDefaultBookCategories(supabaseClient) {
  if (!supabaseClient) return [];

  try {
    const { data: existingRows, error } = await supabaseClient
      .from('categories')
      .select('id, name');

    if (error) throw error;

    const namesInDb = new Set(
      (existingRows || [])
        .map(row => normalizeCategoryName(row.name))
        .filter(Boolean)
    );

    const missing = Array.from(
      new Map(
        UNIQUE_DEFAULT_BOOK_CATEGORIES.map(name => [normalizeCategoryName(name), name])
      ).values()
    ).filter(name => {
      const normalized = normalizeCategoryName(name);
      return normalized && !namesInDb.has(normalized);
    });

    if (missing.length === 0) {
      return existingRows || [];
    }

    const { data: inserted, error: insertError } = await supabaseClient
      .from('categories')
      .insert(missing.map(name => ({ name })))
      .select('id, name');

    if (insertError) throw insertError;

    return [...(existingRows || []), ...(inserted || [])];
  } catch (error) {
    return [];
  }
}
